apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: "82240947"
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJjZXBnYmFzZWFjci5henVyZWNyLmlvIjogewogICAgICAidXNlcm5hbWUiOiAiZTlhNGNjZWQtY2JjOC00MmYwLWFjZjktMDZlNjUzOTZhZDk5IiwKICAgICAgInBhc3N3b3JkIjogInNKbjhRfn5ZbXo5b1RPdllIRWRVNTZYRjdNS05ndU1zcm8wSFNjdW0iLAogICAgICAiZW1haWwiOiAidW91ci1lbWFpbEBleGFtcGxlLmNvbSIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson
